=== ValerieSam/web-v2-i18n/schemas/front/budget.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "entry": {
      "type": "object",
      "properties": {
        "loop": {
          "type": "object",
          "properties": {
            "Month": {
              "$ref": "#/$defs/string"
            },
            "Year": {
              "$ref": "#/$defs/string"
            }
          }
        },
        "message": {
          "type": "object",
          "properties": {
            "DeleteConfirm": {
              "$ref": "#/$defs/string"
            },
            "DeleteConfirmOldNotice": {
              "$ref": "#/$defs/string"
            }
          }
        },
        "property": {
          "type": "object",
          "properties": {
            "Loop": {
              "$ref": "#/$defs/string"
            },
            "Name": {
              "$ref": "#/$defs/string"
            }
          }
        },
        "title": {
          "type": "object",
          "properties": {
            "Create": {
              "$ref": "#/$defs/string"
            },
            "Delete": {
              "$ref": "#/$defs/string"
            }
          }
        },
        "type": {
          "type": "object",
          "properties": {
            "Expense": {
              "$ref": "#/$defs/string"
            },
            "Income": {
              "$ref": "#/$defs/string"
            }
          }
        },
        "validation": {
          "type": "object",
          "properties": {
            "EndDateAfterStartDate": {
              "$ref": "#/$defs/string"
            }
          }
        }
      }
    },
    "page": {
      "type": "object",
      "properties": {
        "Title": {
          "$ref": "#/$defs/string"
        },
        "label": {
          "type": "object",
          "properties": {
            "Budgets": {
              "$ref": "#/$defs/string"
            },
            "Category": {
              "$ref": "#/$defs/string"
            },
            "Difference": {
              "$ref": "#/$defs/string"
            },
            "ExpensesByCategories": {
              "$ref": "#/$defs/string"
            },
            "Fact": {
              "$ref": "#/$defs/string"
            },
            "IncomesByCategories": {
              "$ref": "#/$defs/string"
            },
            "Plan": {
              "$ref": "#/$defs/string"
            },
            "Progress": {
              "$ref": "#/$defs/string"
            }
          }
        }
      }
    },
    "period": {
      "type": "object",
      "properties": {
        "property": {
          "type": "object",
          "properties": {
            "Inherit": {
              "$ref": "#/$defs/string"
            }
          }
        }
      }
    },
    "timeline": {
      "type": "object",
      "properties": {
        "label": {
          "type": "object",
          "properties": {
            "ShowAllCategories": {
              "$ref": "#/$defs/string"
            }
          }
        }
      }
    }
  }
}

=== ValerieSam/web-v2-i18n/locales/en/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "For month",
      "Year": "For year"
    },
    "message": {
      "DeleteConfirm": "Are you sure to delete this budget?",
      "DeleteConfirmOldNotice": "This budget is connected to old budget. If you delete it, and then somebody will change old budget again (either in old web or mobile app with old budget), then new budget will be created automatically instead of this one."
    },
    "property": {
      "Loop": "Period",
      "Name": "Name"
    },
    "title": {
      "Create": "Add budget",
      "Delete": "Delete budget"
    },
    "type": {
      "Expense": "Expenses",
      "Income": "Incomes"
    },
    "validation": {
      "EndDateAfterStartDate": "End date must be after start date"
    }
  },
  "page": {
    "label": {
      "Budgets": "Budgets",
      "Category": "Category",
      "Difference": "Difference",
      "ExpensesByCategories": "Expenses by budget categories:",
      "Fact": "Fact",
      "IncomesByCategories": "Incomes by budget categories:",
      "Plan": "Plan",
      "Progress": "Progress"
    },
    "Title": "Budget"
  },
  "period": {
    "property": {
      "Inherit": "For all future periods"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Show all"
    }
  }
}

=== ValerieSam/web-v2-i18n/locales/ru/front/budget.json
{
  "entry": {
    "loop": {
      "Month": "На месяц",
      "Year": "На год"
    },
    "message": {
      "DeleteConfirm": "Вы действительно хотите удалить данный бюджет?",
      "DeleteConfirmOldNotice": "Этот бюджет связан со старым бюджетом. Если Вы его удалите, а затем кто-либо изменит старый бюджет (на старой веб-версии или в приложении со старым бюджетом), то автоматически создастся новый бюджет вместо этого."
    },
    "property": {
      "Loop": "Период",
      "Name": "Название"
    },
    "title": {
      "Create": "Добавить бюджет",
      "Delete": "Удалить бюджет"
    },
    "type": {
      "Expense": "Расходы",
      "Income": "Доходы"
    },
    "validation": {
      "EndDateAfterStartDate": "Дата окончания должна быть позже даты начала."
    }
  },
  "page": {
    "label": {
      "Budgets": "Бюджеты",
      "Category": "Категория",
      "Difference": "Разница",
      "ExpensesByCategories": "Расходы по категориям бюджета:",
      "Fact": "Факт",
      "IncomesByCategories": "Доходы по категориям бюджета:",
      "Plan": "План",
      "Progress": "Выполнение"
    },
    "Title": "Бюджет"
  },
  "period": {
    "property": {
      "Inherit": "Для всех будущих дат"
    }
  },
  "timeline": {
    "label": {
      "ShowAllCategories": "Показать все"
    }
  }
}
